User Update = c3po v6
# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' postscript_name=JetBrainsMono-Bold
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME

hide_window_decorations yes
# Line
cursor_shape beam
cursor_blink_interval 0

# Exports
include binds






